# frozen_string_literal: true

# Load encoding map if it exists (generated by font_builder.rb).
# When running tests, the test file stubs ENCODING_MAP before requiring this file.
unless defined?(ENCODING_MAP)
  require_relative '../encoding_map'
end

module Converter
  COMMAND_PATTERN = /\A-\w+-\r?\z/

  def self.command_string?(str)
    str.match?(COMMAND_PATTERN)
  end

  # Encode a display string character-by-character using ENCODING_MAP.
  # \r is passed through as-is. Missing characters cause abort.
  def self.encode_string(str)
    result = String.new(encoding: 'BINARY')
    str.each_char do |char|
      if char == "\r"
        result << "\r"
      elsif ENCODING_MAP.key?(char)
        result << ENCODING_MAP[char].chr
      else
        abort "ERROR: No tile mapping for character #{char.inspect} " \
              "(U+#{char.codepoints.first.to_s(16).upcase}). " \
              "Add it to demo04_data.txt's character set and rebuild font_data.h."
      end
    end
    result
  end

  # Format a binary string as a Ruby string literal with \xNN escapes for all bytes.
  def self.format_string(str)
    escaped = str.bytes.map { |b| "\\x%02X" % b }.join
    "\"#{escaped}\""
  end
end

# Main script — only runs when invoked directly, not when required by tests
if __FILE__ == $0
  abort "Usage: converter.rb <text_file>" unless ARGV.size == 1

  File.open(ARGV[0], encoding: 'UTF-8') do |file|
    items = file.read.split(/^:/)
    items = items.reject(&:empty?).map { |i| i.gsub("\n", "\r") }

    pages = []
    current_page = []

    items.each do |item|
      if item.start_with?("---")
        pages.push current_page unless current_page.empty?
        current_page = [item.sub(/^---/, "")]
      else
        current_page.push(item)
      end
    end
    pages.push current_page unless current_page.empty?

    # Encode all display strings; pass command strings through as raw ASCII
    encoded_pages = pages.map do |page|
      page.map do |item|
        if Converter.command_string?(item)
          item.inspect  # emit as a normal Ruby string literal
        else
          Converter.format_string(Converter.encode_string(item))
        end
      end
    end

    puts "pres_data ="
    # Emit the nested array manually to preserve \xNN escaping
    puts "["
    encoded_pages.each_with_index do |page, pi|
      print "  ["
      print page.join(", ")
      print "]"
      print "," unless pi == encoded_pages.size - 1
      puts
    end
    puts "]"
    puts
  end
end
