# frozen_string_literal: true

module FontBuilder
  # Parse a BDF font file string.
  # Returns a Hash of { codepoint(Integer) => [8 bytes] }
  # Uses FONT_ASCENT and per-glyph BBX to position each glyph correctly in the 8-row tile.
  def self.parse_bdf(content)
    glyphs = {}
    font_ascent = nil
    codepoint = nil
    bbx = nil       # [width, height, xoff, yoff]
    bitmap_rows = nil

    content.each_line do |line|
      line = line.strip
      if line.start_with?('FONT_ASCENT ')
        font_ascent ||= line.split(' ', 2)[1].to_i
      elsif line.start_with?('ENCODING ')
        codepoint = line.split(' ', 2)[1].to_i
        codepoint = nil if codepoint&.negative?
        bbx = nil
        bitmap_rows = nil
      elsif line.start_with?('BBX ')
        parts = line.split
        bbx = [parts[1].to_i, parts[2].to_i, parts[3].to_i, parts[4].to_i]
      elsif line == 'BITMAP'
        bitmap_rows = []
      elsif bitmap_rows && line == 'ENDCHAR'
        if codepoint && bbx
          _width, height, xoff, yoff = bbx
          ascent = font_ascent || 6
          # tile_row for the topmost bitmap row: ascent - yoff - height
          top_tile_row = ascent - yoff - height

          tile = Array.new(8, 0)
          bitmap_rows.each_with_index do |byte, i|
            tile_row = top_tile_row + i
            next if tile_row < 0 || tile_row > 7
            tile[tile_row] = (byte >> xoff) & 0xFF
          end
          glyphs[codepoint] = tile
        end
        codepoint = nil
        bbx = nil
        bitmap_rows = nil
      elsif bitmap_rows
        bitmap_rows << line[0, 2].to_i(16)
      end
    end

    glyphs
  end

  # Parse a standard_font binary file (FONT8.BIN format).
  # 256 characters × 8 bytes each, raw 1bpp binary.
  # Returns a Hash of { codepoint(Integer) => [8 bytes] }
  def self.parse_standard_font_bin(binary_content)
    bytes = binary_content.bytes
    (0..255).each_with_object({}) do |codepoint, glyphs|
      glyphs[codepoint] = bytes[codepoint * 8, 8] || ([0] * 8)
    end
  end

  COMMAND_PATTERN = /\A-\w+-\r?\z/

  # Scan text content for all unique displayable characters.
  # Skips \r and any item that is a command string (/-\w+-\r?$/).
  # Returns a sorted array of unique character strings.
  def self.scan_characters(text)
    text = text.gsub("\n", "\r")
    chars = []
    text.each_line("\r") do |item|
      next if item.strip.empty?
      next if item.match?(COMMAND_PATTERN)
      item.each_char do |c|
        next if c == "\r"
        chars << c
      end
    end
    chars.uniq.sort_by { |c| c.codepoints.first }
  end

  RESERVED_INDICES = [0x00, 0x0C, 0x0D].freeze

  # Assign tile indices to an array of character strings.
  # Indices start at 0 and skip RESERVED_INDICES (0x00 = null, 0x0C = FF/CLS in SMS stdio, 0x0D = CR),
  # so the first assigned index is 1. Max index is 255 (single-byte SMS tile).
  # Returns a Hash of { char_string => tile_index }.
  def self.assign_indices(characters)
    map = {}
    index = 0
    characters.each do |char|
      index += 1 while RESERVED_INDICES.include?(index)
      abort "ERROR: Too many unique characters (#{map.size + 1}); tile index #{index} exceeds 255. Reduce the character set." if index > 255
      map[char] = index
      index += 1
    end
    map
  end

  PLACEHOLDER_GLYPH = [0] * 8

  # Generate C header source for the custom font.
  # map:    { char_string => tile_index }
  # glyphs: { codepoint(Integer) => [8 bytes] }
  # Tile indices are 1-based; the generated array covers tiles 1..max_index.
  def self.generate_font_data_h(map, glyphs)
    count = map.values.max || 0
    # Build array indexed by tile position (1-based); index 0 unused.
    tiles = Array.new(count + 1) { PLACEHOLDER_GLYPH.dup }

    map.each do |char, idx|
      codepoint = char.codepoints.first
      glyph = glyphs[codepoint]
      if glyph.nil?
        warn "WARNING: No glyph found for U+#{codepoint.to_s(16).upcase} (#{char.inspect}); using blank tile"
        glyph = PLACEHOLDER_GLYPH.dup
      end
      tiles[idx] = glyph
    end

    lines = []
    lines << "/* Auto-generated by scripts/font_builder.rb — do not edit */"
    lines << "#ifndef FONT_DATA_H"
    lines << "#define FONT_DATA_H"
    lines << ""
    lines << "#define DEMO04_FONT_TILE_COUNT #{count}"
    lines << ""
    lines << "const uint8_t demo04_font[] = {"
    (1..count).each do |i|
      row = tiles[i].map { |b| "0x%02X" % b }.join(", ")
      lines << "  #{row}, /* tile #{i} */"
    end
    lines << "};"
    lines << ""
    lines << "#endif /* FONT_DATA_H */"
    lines.join("\n") + "\n"
  end

  # Generate the encoding_map.rb source file.
  # map: { char_string => tile_index }
  def self.generate_encoding_map_rb(map)
    lines = []
    lines << "# frozen_string_literal: true"
    lines << "# Auto-generated by scripts/font_builder.rb — do not edit"
    lines << "ENCODING_MAP = {"
    map.sort_by { |_, idx| idx }.each do |char, idx|
      lines << "  #{char.inspect} => #{idx},"
    end
    lines << "}.freeze"
    lines.join("\n") + "\n"
  end
end

if __FILE__ == $0
  abort "Usage: font_builder.rb <text_file> <bdf_file> <standard_font_bin> <encoding_map_out> <font_data_out>" unless ARGV.size == 5

  text_file, bdf_file, standard_font_bin, encoding_map_out, font_data_out = ARGV

  abort "Text file not found: #{text_file}"          unless File.exist?(text_file)
  abort "BDF file not found: #{bdf_file}"            unless File.exist?(bdf_file)
  abort "Standard font not found: #{standard_font_bin}" unless File.exist?(standard_font_bin)

  text_content = File.read(text_file,         encoding: 'UTF-8')
  bdf_content  = File.read(bdf_file,          encoding: 'UTF-8')
  bin_content  = File.read(standard_font_bin, encoding: 'BINARY')

  bdf_glyphs = FontBuilder.parse_bdf(bdf_content)
  bin_glyphs = FontBuilder.parse_standard_font_bin(bin_content)

  # ASCII range (codepoints 0x00-0x7F) comes from standard_font; everything else from BDF.
  glyphs = bdf_glyphs.merge(bin_glyphs.select { |cp, _| cp <= 0x7F })

  characters = FontBuilder.scan_characters(text_content)
  char_map   = FontBuilder.assign_indices(characters)

  puts "Found #{characters.size} unique characters, #{char_map.values.max} tile indices used."

  File.write(font_data_out,    FontBuilder.generate_font_data_h(char_map, glyphs))
  File.write(encoding_map_out, FontBuilder.generate_encoding_map_rb(char_map))

  puts "Written: #{font_data_out}"
  puts "Written: #{encoding_map_out}"
end
